---
title: 'University of Melbourne Resources'
teaching: 10
exercises: 2
---
:::::::::::::::::::::::::::::::::::::: questions 

- What do you need to abide by when managing research data at UoM? 
- What tools and systems are available to you? 
- Where can you go for help with research data issues? 

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Understand how to meet your research data responsibilities at the University 
- Identify appropriate tools and systems to manage your data 
- Become familiar with available support and resources 

::::::::::::::::::::::::::::::::::::::::::::::::

## Overview

Ensuring you meet your research data management obligations while doing research can feel overwhelming and stressful. The University has many resources, including systems, training and support teams to make this process as easy as possible.   

## UoM RDM Policy

Research data management responsibilities in Australia are set out in federal and state legislation and in the [Australian Code for the Responsible Conduct of Research](https://www.nhmrc.gov.au/about-us/publications/australian-code-responsible-conduct-research-2018). These responsibilities have been translated into the University context by the [Research Data Management Policy (MPF1242)](https://policy.unimelb.edu.au/MPF1242). All UoM researchers must abide by this policy. 

The overarching principles in this policy are that: 

* Research be recorded in ways that allow for the scrutiny of research results, supporting research integrity. 
* Research data and records be managed safely and securely to meet ethical requirements, protect researchers, participants, and the University. 
* Research data and records be retained for minimum periods under the University’s responsibilities as a public institution 
* Wherever possible, research data be made available for access and reuse by the community, maximising the value of research investment. 

It is important to note that international mandates (e.g., the European Union General Data Protection Regulation) or specific legal agreements such as contracts or data sharing agreements can also impact data management responsibilities but are not addressed in the policy. 

## Training and support

The following resources are provided by the University to help you manage your research data and meet your research data responsibilities more easily:

* [Managing Data @Melbourne](https://canvas.lms.unimelb.edu.au/courses/83782) is a Canvas training course that covers practical steps to manage your data, including completing a Research Data Management Plan
*	[Research Data Services Directory](https://dataservices.research.unimelb.edu.au/) is a searchable directory of all tools, services and training available at the University, including academic units such as the Melbourne Data Analytics Platform
*	[Research Data Systems Finder](https://dataservices.research.unimelb.edu.au/finder/) is a tool to filter and compare available research data systems to determine systems best suited to your research
*	[Research Data Management resources on the Research Gateway](https://gateway.research.unimelb.edu.au/platforms-data-and-reporting/data-and-computation/research-data-management) provide information about different aspects of RDM, including how to securely manage sensitive data to publishing and retaining data
*	[Research Computing Services](https://gateway.research.unimelb.edu.au/platforms-data-and-reporting/data-and-computation/research-computing-services-rcs) manages the University’s large-scale research data storage, cloud computing and High-Performance Computing (HPC) and can help you setup accounts and allocate resources for your research
*	Need more help? You can [submit a ticket through ServiceNow](https://uomservicehub.service-now.com/esc?id=sc_cat_item&sys_id=56b3a10e1b5e1190ef32a68b274bcb80) to request specific advice on your research data management requirements


::::::::::::::::::::::::::::::::::::: keypoints 

- All UoM research must abide by the RDM Policy
- The University provides many services to help you
- Don’t hesitate to reach out if you need more help


::::::::::::::::::::::::::::::::::::::::::::::::

